### ISSUE TITLE
Travis for 7.0

### ISSUE THREAD

**Issue by yvaucher** [OCA/vertical-ngo#2]
addons-backport needs to be used
https://launchpad.net/openerp-humanitarian-ngo/addons-backport

**Comment by bwrsandman** [comment]
@yvaucher is this still the case?

Why can't the modules be brought here individually?

**Comment by yvaucher** [comment]
@bwrsandman purchase_requisition extention modules are depending on backport of 8.0 addons into 7.0

So I think it is still required.

@nbessi Do you confirm?

**Comment by gurneyalex** [comment]
@yvaucher @bwrsandman I confirm. 

It's even worse than that: they depend on backports of some intermediate version of the 8.0 addons in 7.0 which make them unsuitable for "normal" use in 7.0.

**Comment by bwrsandman** [comment]
Closing the issue as it is marked `wontfix`
