### ISSUE TITLE
Travis SyntaxWarning on logistics requisition test

### ISSUE THREAD

**Issue by yvaucher** [OCA/vertical-ngo#40]
/home/travis/build/OCA/vertical-ngo/logistic_requisition/test/requisition_sourcing_with_tender.yml:131: SyntaxWarning: assertion is always true, perhaps remove parentheses?

To check

**Comment by gurneyalex** [comment]
@lepistone while you are in the tests, could you look into this?

**Comment by lepistone** [comment]
done, well spotted.
